server:
  port: 5000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flowopendev
    username: developer
    password: developer

---
environment: prod
server:
  port: 7070

---
environment: test
server:
  port: 4000
